package track.place.com.entities.enums;

public enum Label {

    Epic,
    Story,
    Task,
    Subtask,
    Bug,
    Improvement,
    Feature,
    Research,
    Documentation,
    Design,
    Testing,
    Review,
    Deployment,
    Maintenance,
    Analysis,
    Planning,
    Communication,
    Collaboration,
    Reporting,
    Monitoring,
    Configuration,
    Integration,
    Optimization,
    Refactoring,
    DocumentationUpdate,
    QualityAssurance,
    UserExperience,
    Security,
    Performance,
    Accessibility,

}
